/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrackingIndexRouteImport } from './routes/tracking/index'
import { Route as SignMakerIndexRouteImport } from './routes/sign-maker/index'
import { Route as ScanIndexRouteImport } from './routes/scan/index'
import { Route as ApiCronRouteImport } from './routes/api/cron'
import { Route as ScanProductSkuRouteImport } from './routes/scan/product.$sku'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackingIndexRoute = TrackingIndexRouteImport.update({
  id: '/tracking/',
  path: '/tracking/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignMakerIndexRoute = SignMakerIndexRouteImport.update({
  id: '/sign-maker/',
  path: '/sign-maker/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanIndexRoute = ScanIndexRouteImport.update({
  id: '/scan/',
  path: '/scan/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronRoute = ApiCronRouteImport.update({
  id: '/api/cron',
  path: '/api/cron',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanProductSkuRoute = ScanProductSkuRouteImport.update({
  id: '/scan/product/$sku',
  path: '/scan/product/$sku',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/api/cron': typeof ApiCronRoute
  '/scan': typeof ScanIndexRoute
  '/sign-maker': typeof SignMakerIndexRoute
  '/tracking': typeof TrackingIndexRoute
  '/scan/product/$sku': typeof ScanProductSkuRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/api/cron': typeof ApiCronRoute
  '/scan': typeof ScanIndexRoute
  '/sign-maker': typeof SignMakerIndexRoute
  '/tracking': typeof TrackingIndexRoute
  '/scan/product/$sku': typeof ScanProductSkuRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/api/cron': typeof ApiCronRoute
  '/scan/': typeof ScanIndexRoute
  '/sign-maker/': typeof SignMakerIndexRoute
  '/tracking/': typeof TrackingIndexRoute
  '/scan/product/$sku': typeof ScanProductSkuRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/api/cron'
    | '/scan'
    | '/sign-maker'
    | '/tracking'
    | '/scan/product/$sku'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/api/cron'
    | '/scan'
    | '/sign-maker'
    | '/tracking'
    | '/scan/product/$sku'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/signup'
    | '/api/cron'
    | '/scan/'
    | '/sign-maker/'
    | '/tracking/'
    | '/scan/product/$sku'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiCronRoute: typeof ApiCronRoute
  ScanIndexRoute: typeof ScanIndexRoute
  SignMakerIndexRoute: typeof SignMakerIndexRoute
  TrackingIndexRoute: typeof TrackingIndexRoute
  ScanProductSkuRoute: typeof ScanProductSkuRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracking/': {
      id: '/tracking/'
      path: '/tracking'
      fullPath: '/tracking'
      preLoaderRoute: typeof TrackingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-maker/': {
      id: '/sign-maker/'
      path: '/sign-maker'
      fullPath: '/sign-maker'
      preLoaderRoute: typeof SignMakerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan/': {
      id: '/scan/'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron': {
      id: '/api/cron'
      path: '/api/cron'
      fullPath: '/api/cron'
      preLoaderRoute: typeof ApiCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan/product/$sku': {
      id: '/scan/product/$sku'
      path: '/scan/product/$sku'
      fullPath: '/scan/product/$sku'
      preLoaderRoute: typeof ScanProductSkuRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiCronRoute: ApiCronRoute,
  ScanIndexRoute: ScanIndexRoute,
  SignMakerIndexRoute: SignMakerIndexRoute,
  TrackingIndexRoute: TrackingIndexRoute,
  ScanProductSkuRoute: ScanProductSkuRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
